import re
import os
import pathlib

oss_output_dir = os.path.join('output', 'popular')
minified_output_dir = os.path.join('output')

all_packages = [pathlib.Path(f).stem for f in os.listdir(oss_output_dir) if os.path.isfile(os.path.join(oss_output_dir, f))]

with open(os.path.join(minified_output_dir, 'targets.csv'), 'w') as targets_file,   \
    open(os.path.join(minified_output_dir, 'confusers.csv'), 'w') as confusers_file:
    targets_file.write('target_pkg,confuser_pkgs\n')
    confusers_file.write('confuser_pkg,target_pkg,signals\n')
    
    for pkg_name in all_packages:
        print(f'Processing {pkg_name}...')
        with open(os.path.join(oss_output_dir, f'{pkg_name}.txt'), 'r') as log_file:
            confusers = []

            for log_line in log_file:
                pattern_confuser = r"(?<=Potential Squat candidate ')[^']+"
                match_confuser = re.search(pattern_confuser, log_line)
                confuser = match_confuser.group()

                pattern_signals = r"(?<=Generated by ).*?(?=\.$)"
                match_signals = re.search(pattern_signals, log_line)

                pattern_commas = r"(?<=[^\s]),(?=[^\s])"
                signals = re.sub(pattern_commas, ";", match_signals.group())

                confusers_file.write(f'{confuser},{pkg_name},{signals}\n')

                confusers.append(confuser)
            
            squats_str = ';'.join(confusers)
            targets_file.write(f'{pkg_name},{squats_str}\n')