import re
import os
import pathlib

oss_output_dir = os.path.join('output', 'ossgadget')
minified_output_dir = os.path.join('output')

with open(os.path.join(minified_output_dir, 'targets.csv'), 'w') as targets_file,   \
    open(os.path.join(minified_output_dir, 'confusers.csv'), 'w') as confusers_file:
    targets_file.write('target_pkg,confuser_pkgs\n')
    confusers_file.write('confuser_pkg,target_pkg,signals\n')
    
    with open(os.path.join(oss_output_dir, f'output.txt'), 'r') as log_file:
        confusers = []
        cur_pkg_name = ""

        for log_line in log_file:
            pattern_pkg_name = r"^[^:]+"
            match_pkg_name = re.search(pattern_pkg_name, log_line)
            pkg_name = match_pkg_name.group()

            # new target package found
            if cur_pkg_name != pkg_name:        
                # this is NOT the first instance of the package, so process last package        
                if cur_pkg_name != "":
                    squats_str = ';'.join(confusers)
                    targets_file.write(f'{cur_pkg_name},{squats_str}\n')
                    confusers = []
                
                print(f'Processing {pkg_name}...')
                cur_pkg_name = pkg_name


            pattern_confuser = r"(?<=Potential Squat candidate ')[^']+"
            match_confuser = re.search(pattern_confuser, log_line)
            confuser = match_confuser.group()

            pattern_signals = r"(?<=Generated by ).*?(?=\.$)"
            match_signals = re.search(pattern_signals, log_line)

            pattern_commas = r"(?<=[^\s]),(?=[^\s])"
            signals = re.sub(pattern_commas, ";", match_signals.group())

            confusers_file.write(f'{confuser},{pkg_name},{signals}\n')

            confusers.append(confuser)
            
        # process last target package
        squats_str = ';'.join(confusers)
        targets_file.write(f'{cur_pkg_name},{squats_str}\n')
        confusers = []